// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $CardIslands from "./islands/CardIslands.tsx";
import * as $CardIslandsServices from "./islands/CardIslandsServices.tsx";
import * as $CareersIsland from "./islands/CareersIsland.tsx";
import * as $CarouselIsland from "./islands/CarouselIsland.tsx";
import * as $CarouselIslandServices from "./islands/CarouselIslandServices.tsx";
import * as $ImageParallax from "./islands/ImageParallax.tsx";
import * as $LanguageSelector from "./islands/LanguageSelector.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/CardIslands.tsx": $CardIslands,
    "./islands/CardIslandsServices.tsx": $CardIslandsServices,
    "./islands/CareersIsland.tsx": $CareersIsland,
    "./islands/CarouselIsland.tsx": $CarouselIsland,
    "./islands/CarouselIslandServices.tsx": $CarouselIslandServices,
    "./islands/ImageParallax.tsx": $ImageParallax,
    "./islands/LanguageSelector.tsx": $LanguageSelector,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
