// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Accordion-hero.tsx";
import * as $$$$$$1 from "./sections/BlogPosts.tsx";
import * as $$$$$$15 from "./sections/careers/Careers.tsx";
import * as $$$$$$16 from "./sections/careers/descriptionCareers/DescriptionCareers.tsx";
import * as $$$$$$17 from "./sections/careers/formCareers/FormCareers.tsx";
import * as $$$$$$18 from "./sections/careers/searchCareers/SearchCareers.tsx";
import * as $$$$$$19 from "./sections/careers/waveCareers/WaveCareers.tsx";
import * as $$$$$$2 from "./sections/Carousel.tsx";
import * as $$$$$$3 from "./sections/Faq.tsx";
import * as $$$$$$4 from "./sections/Footer.tsx";
import * as $$$$$$5 from "./sections/Form.tsx";
import * as $$$$$$6 from "./sections/Header.tsx";
import * as $$$$$$20 from "./sections/hero-1.tsx";
import * as $$$$$$21 from "./sections/hero-2.tsx";
import * as $$$$$$7 from "./sections/Hero.tsx";
import * as $$$$$$22 from "./sections/hero2.tsx";
import * as $$$$$$8 from "./sections/HeroBanner.tsx";
import * as $$$$$$9 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$10 from "./sections/Logos.tsx";
import * as $$$$$$11 from "./sections/ParallaxCard.tsx";
import * as $$$$$$12 from "./sections/ServiceCards.tsx";
import * as $$$$$$13 from "./sections/Testimonials.tsx";
import * as $$$$$$14 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Accordion-hero.tsx": $$$$$$0,
    "site/sections/BlogPosts.tsx": $$$$$$1,
    "site/sections/careers/Careers.tsx": $$$$$$15,
    "site/sections/careers/descriptionCareers/DescriptionCareers.tsx": $$$$$$16,
    "site/sections/careers/formCareers/FormCareers.tsx": $$$$$$17,
    "site/sections/careers/searchCareers/SearchCareers.tsx": $$$$$$18,
    "site/sections/careers/waveCareers/WaveCareers.tsx": $$$$$$19,
    "site/sections/Carousel.tsx": $$$$$$2,
    "site/sections/Faq.tsx": $$$$$$3,
    "site/sections/Footer.tsx": $$$$$$4,
    "site/sections/Form.tsx": $$$$$$5,
    "site/sections/Header.tsx": $$$$$$6,
    "site/sections/hero-1.tsx": $$$$$$20,
    "site/sections/hero-2.tsx": $$$$$$21,
    "site/sections/Hero.tsx": $$$$$$7,
    "site/sections/hero2.tsx": $$$$$$22,
    "site/sections/HeroBanner.tsx": $$$$$$8,
    "site/sections/ImageWithParagraph.tsx": $$$$$$9,
    "site/sections/Logos.tsx": $$$$$$10,
    "site/sections/ParallaxCard.tsx": $$$$$$11,
    "site/sections/ServiceCards.tsx": $$$$$$12,
    "site/sections/Testimonials.tsx": $$$$$$13,
    "site/sections/Theme/Theme.tsx": $$$$$$14,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
